service: upload-to-s3-with-signedUrl

frameworkVersion: "3"

# Specify your bucket name here
custom:
  bucketName: imageinfoarchive
  stage: ${opt:stage, self:provider.stage}
  region: ${opt:region, self:provider.region}

provider:
  name: aws
  runtime: nodejs14.x
  stage: test # change the stage if you want
  region: us-east-1 # change the region if you want
  stackName: ${self:custom.bucketName} 
  apiName: ${self:custom.bucketName} 
  endpointType: regional
  memorySize: 128
  vpc:
    securityGroupIds: ${file(config/${opt:stage,self:provider.stage}/vpc.yml):security}
    subnetIds: ${file(config/${opt:stage,self:provider.stage}/vpc.yml):subnets}
  deploymentBucket: iia-short-lived
	
package: #exclude frontend folder and files on deploy
  patterns:
    - '!frontend/**'

functions: # lambda function
  upload:
    role: arn:aws:iam::719579466865:role/test-iia-lambda
    handler: index.handler
    name: ${self:custom.bucketName}
    environment:
      UploadBucket: ${self:custom.bucketName}
    events:
      - http: # create a api gateway to trigger de lambda function
          path: /${self:custom.bucketName}
          method: get
          cors: true

resources:
  Resources:
    UploadBucket:  # create a s3 bucket
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:custom.bucketName}
        AccessControl: PublicRead
        CorsConfiguration: # define cors
          CorsRules:
            - AllowedHeaders:
                - "*"
              AllowedMethods:
                - GET
                - HEAD
                - PUT
                - POST
                - DELETE
              AllowedOrigins:
                - "*"
    UploadBucketPolicy: # define policy to bucket and objects
      Type: AWS::S3::BucketPolicy
      Properties:
        Bucket:
          Ref: UploadBucket
        PolicyDocument:
          Statement:
            - Effect: "Allow"
              Action:
                - s3:GetObject # defined public access only to get the objects on the bucket.
              Principal: "*"
              Sid: PublicGetObject
              Resource:
                Fn::Join:
                  - ""
                  - - "arn:aws:s3:::"
                    - "Ref": UploadBucket
                    - "/*"
